[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/influxdata/influxdb"
  version = "1.6.0"

[[constraint]]
  branch = "master"
  name = "github.com/davidsteinsland/ynab-go"
