[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/influxdata/influxdb"
  version = "1.6.0"

[[constraint]]
  branch = "master"
  name = "github.com/davidsteinsland/ynab-go"

[[constraint]]
  name = "github.com/robfig/cron"
  version = "1.1.0"

[[constraint]]
  name = "github.com/fabioberger/airtable-go"
  version = "3.1.0"

[[constraint]]
  name = "github.com/lib/pq"
  version = "1.0.0"
