version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Update Define Environment Variables
          command: |
            echo 'export TAG=$CIRCLE_SHA1' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Building docker image
          command: |
            docker build -t benjamincaldwell/selfops .
      - run:
          name: Pushing docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag benjamincaldwell/selfops benjamincaldwell/selfops:$TAG
            docker push benjamincaldwell/selfops
            docker push benjamincaldwell/selfops:$TAG

  deploy:
    docker:
      - image: docker:18.06.0-ce
    environment:
      CLUSTER_DOMAIN: benjamincaldwell.ca
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "80:58:cd:21:56:5a:81:10:54:58:0c:a3:d1:4b:04:b8"

      - run:
          name: Install ssh
          command: |
            apk update
            apk add openssh

      - run:
          name: Deploying
          command: |
            export DOCKER_TAG=$CIRCLE_SHA1
            echo "${DOCKER_TAG}"
            ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -NL 0.0.0.0:2374:/var/run/docker.sock ${DOCKER_SWARM_USER}@${DOCKER_SWARM_HOST} &
            export TUNNEL_PID=$!
            sleep 1
            docker -H localhost:2374 stack deploy --compose-file deploy/selfops.yml selfops
            kill -9 ${TUNNEL_PID}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
