version: "3.5"
services:
  influxdb:
    image: influxdb:1.6.0-alpine
    deploy:
      placement:
        constraints:
          - node.hostname == swarm-2
    environment:
      - INFLUXDB_DATA_ENGINE=tsm1
      - INFLUXDB_REPORTING_DISABLED=false
    volumes:
      - influxdb-data:/var/lib/influxdb
    networks:
      - influxdb

networks:
  influxdb:
    external: true
    # driver: overlay
    # name: influxdb

volumes:
  influxdb-data:
