version: "3.5"
services:
  influxdb:
    image: influxdb:1.6.0-alpine
    environment:
      - INFLUXDB_DATA_ENGINE=tsm1
      - INFLUXDB_REPORTING_DISABLED=false
    # volumes:
    #   - influxdb-data:/var/lib/influxdb
    networks:
      - influxdb

networks:
  influxdb:
    driver: overlay
    name: influxdb

# volumes:
#   influxdb-data:
