version: "3.5"
services:
  postgres:
    image: postgres:11-alpine
    deploy:
      placement:
        constraints:
          - node.hostname == swarm-2
    environment:
      - POSTGRES_USER=selfops
      - POSTGRES_DB=ynab
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres
    secrets:
      - source: postgres-password
        target: /run/secrets/postgres-passwd

networks:
  postgres:
    external: true
    # driver: overlay
    # name: postgres

volumes:
  postgres-data:

secrets:
  postgres-password:
    external: true
