version: "3.5"
services:
  ynabImporter:
    image: benjamincaldwell/selfops:${DOCKER_TAG-latest}
    command:
      - ynab
    secrets:
      - source: selfops-secret
        target: /selfops/secrets.json
    configs:
      - source: selfops-config-oct-29-2019
        target: /selfops/config.yml
    networks:
      - influxdb
      - postgres

  airtableImpoter:
    image: benjamincaldwell/selfops:${DOCKER_TAG-latest}
    command:
      - airtable
    secrets:
      - source: selfops-secret
        target: /selfops/secrets.json
    configs:
      - source: selfops-config-oct-29-2019
        target: /selfops/config.yml
    networks:
      - influxdb

networks:
  influxdb:
    external: true
  postgres:
    external: true

secrets:
  selfops-secret:
    external: true

configs:
  selfops-config-oct-29-2019:
    external: true
