version: "3.5"
services:
  ynabImporter:
    image: benjamincaldwell/selfops:${DOCKER_TAG-latest}
    command:
      - ynab
    environment:
      - YNAB_IMPORTER_EJSON_SECRET_KEY=/run/secrets/ejson/key
    secrets:
      - source: selfops-secret
        target: /selfops/secrets.json
    configs:
      - source: selfops-config-oct-29-2019
        target: /selfops/config.yml
    networks:
      - influxdb
      - postgres

  airtableImpoter:
    image: benjamincaldwell/selfops:${DOCKER_TAG-latest}
    command:
      - airtable
    secrets:
      - source: selfops-secret-nov-03-2019
        target: /selfops/secrets.ejson
      - source: ynab-importers-ejson-key
        target: /run/secrets/ejson/key
    configs:
      - source: selfops-config-oct-29-2019
        target: /selfops/config.yml
    networks:
      - influxdb

networks:
  influxdb:
    external: true
  postgres:
    external: true

secrets:
  selfops-secret-nov-03-2019:
    external: true
  ynab-importers-ejson-key:
    external: true

configs:
  selfops-config-oct-29-2019:
    external: true
